### ISSUE TITLE
complete Likelihood

### ISSUE THREAD

**Issue by antolonappan** [antolonappan/marcia#17]

**Comment by Sandeepharidasu** [comment]
To make the CC and BAO likelihood..

[Likelihood_GP_save.py.txt](https://github.com/antolonappan/marcia/files/11469718/Likelihood_GP_save.py.txt)

**Comment by Sandeepharidasu** [comment]
[Run_GP.py.txt](https://github.com/antolonappan/marcia/files/11469771/Run_GP.py.txt)

**Comment by antolonappan** [comment]
Ok, let me check it

**Comment by antolonappan** [comment]
Ok, I will check that

**Comment by antolonappan** [comment]
ok I will check it

**Comment by antolonappan** [comment]
Done in https://github.com/antolonappan/marcia/commit/58ab2bcc815a4e5524c9db6766d30f37955dfcf8
