### ISSUE TITLE
Inclusion of data files(individual)

### ISSUE THREAD

**Issue by Sandeepharidasu** [antolonappan/marcia#4]
We need to acquire the latest SN, GRB and Quasars data, at the least. Anto let's try to do it together, whatever you have please add ..

**Comment by antolonappan** [comment]
My dataset of these probes are very old: https://github.com/antolonappan/cosmopass/tree/master/cosmopass/likelihoods/Data

**Comment by Sandeepharidasu** [comment]
ok .. so it seems the quasars data needs some update too .. and also that I should do some pre-processing for the SNe data .. 
- Added BAO data in simple reduced forms the labels are in the file and cov matric can be loaded directly.

**Comment by antolonappan** [comment]
For GRB, the nuisance parameters are $\lambda$ and $b$ ?

**Comment by antolonappan** [comment]
- [ ] GRB
- [ ] Pantheon
- [ ] Quasars
- [ ] Zhao2018

**Comment by Sandeepharidasu** [comment]
> For GRB, the nuisance parameters are λ and b ?
> 
> The GRB file already has μ and dμ

but ya those are made assuming a LCDM cosmology.. we have to use the nuisance parameters marginalising over them ..

**Comment by antolonappan** [comment]
solved in https://github.com/antolonappan/marcia/commit/b3bd1d07816af1271cd9376508985dfae9f6ed8b
